# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: furnace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='furnace.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rfurnace.proto\x12\x05proto\"\x15\n\x05Stack\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x07Proceed\x12\x0e\n\x06\x66\x61iled\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty24\n\tPreCreate\x12\'\n\x07\x45xecute\x12\x0c.proto.Stack\x1a\x0e.proto.Proceed23\n\nPostCreate\x12%\n\x07\x45xecute\x12\x0c.proto.Stack\x1a\x0c.proto.Empty24\n\tPreDelete\x12\'\n\x07\x45xecute\x12\x0c.proto.Stack\x1a\x0e.proto.Proceed23\n\nPostDelete\x12%\n\x07\x45xecute\x12\x0c.proto.Stack\x1a\x0c.proto.Emptyb\x06proto3')
)




_STACK = _descriptor.Descriptor(
  name='Stack',
  full_name='proto.Stack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Stack.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=45,
)


_PROCEED = _descriptor.Descriptor(
  name='Proceed',
  full_name='proto.Proceed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed', full_name='proto.Proceed.failed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=72,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='proto.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['Stack'] = _STACK
DESCRIPTOR.message_types_by_name['Proceed'] = _PROCEED
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stack = _reflection.GeneratedProtocolMessageType('Stack', (_message.Message,), dict(
  DESCRIPTOR = _STACK,
  __module__ = 'furnace_pb2'
  # @@protoc_insertion_point(class_scope:proto.Stack)
  ))
_sym_db.RegisterMessage(Stack)

Proceed = _reflection.GeneratedProtocolMessageType('Proceed', (_message.Message,), dict(
  DESCRIPTOR = _PROCEED,
  __module__ = 'furnace_pb2'
  # @@protoc_insertion_point(class_scope:proto.Proceed)
  ))
_sym_db.RegisterMessage(Proceed)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'furnace_pb2'
  # @@protoc_insertion_point(class_scope:proto.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_PRECREATE = _descriptor.ServiceDescriptor(
  name='PreCreate',
  full_name='proto.PreCreate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=83,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='proto.PreCreate.Execute',
    index=0,
    containing_service=None,
    input_type=_STACK,
    output_type=_PROCEED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRECREATE)

DESCRIPTOR.services_by_name['PreCreate'] = _PRECREATE


_POSTCREATE = _descriptor.ServiceDescriptor(
  name='PostCreate',
  full_name='proto.PostCreate',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=137,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='proto.PostCreate.Execute',
    index=0,
    containing_service=None,
    input_type=_STACK,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTCREATE)

DESCRIPTOR.services_by_name['PostCreate'] = _POSTCREATE


_PREDELETE = _descriptor.ServiceDescriptor(
  name='PreDelete',
  full_name='proto.PreDelete',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=190,
  serialized_end=242,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='proto.PreDelete.Execute',
    index=0,
    containing_service=None,
    input_type=_STACK,
    output_type=_PROCEED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDELETE)

DESCRIPTOR.services_by_name['PreDelete'] = _PREDELETE


_POSTDELETE = _descriptor.ServiceDescriptor(
  name='PostDelete',
  full_name='proto.PostDelete',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  serialized_start=244,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='proto.PostDelete.Execute',
    index=0,
    containing_service=None,
    input_type=_STACK,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTDELETE)

DESCRIPTOR.services_by_name['PostDelete'] = _POSTDELETE

# @@protoc_insertion_point(module_scope)
