# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import furnace_pb2 as furnace__pb2


class PreCreateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.unary_unary(
        '/proto.PreCreate/Execute',
        request_serializer=furnace__pb2.Stack.SerializeToString,
        response_deserializer=furnace__pb2.Proceed.FromString,
        )


class PreCreateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PreCreateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.unary_unary_rpc_method_handler(
          servicer.Execute,
          request_deserializer=furnace__pb2.Stack.FromString,
          response_serializer=furnace__pb2.Proceed.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.PreCreate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PostCreateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.unary_unary(
        '/proto.PostCreate/Execute',
        request_serializer=furnace__pb2.Stack.SerializeToString,
        response_deserializer=furnace__pb2.Empty.FromString,
        )


class PostCreateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PostCreateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.unary_unary_rpc_method_handler(
          servicer.Execute,
          request_deserializer=furnace__pb2.Stack.FromString,
          response_serializer=furnace__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.PostCreate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PreDeleteStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.unary_unary(
        '/proto.PreDelete/Execute',
        request_serializer=furnace__pb2.Stack.SerializeToString,
        response_deserializer=furnace__pb2.Proceed.FromString,
        )


class PreDeleteServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PreDeleteServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.unary_unary_rpc_method_handler(
          servicer.Execute,
          request_deserializer=furnace__pb2.Stack.FromString,
          response_serializer=furnace__pb2.Proceed.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.PreDelete', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PostDeleteStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Execute = channel.unary_unary(
        '/proto.PostDelete/Execute',
        request_serializer=furnace__pb2.Stack.SerializeToString,
        response_deserializer=furnace__pb2.Empty.FromString,
        )


class PostDeleteServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Execute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PostDeleteServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Execute': grpc.unary_unary_rpc_method_handler(
          servicer.Execute,
          request_deserializer=furnace__pb2.Stack.FromString,
          response_serializer=furnace__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.PostDelete', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
